import os

KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")
SOCIAL_POSTS_TOPIC = os.getenv("SOCIAL_POSTS_TOPIC", "BlueSky_socialmedia_posts")
KAFKA_ACKS = os.getenv("KAFKA_ACKS", "all")
KAFKA_PRODUCER_RETRIES = int(os.getenv("KAFKA_PRODUCER_RETRIES", "5"))
KAFKA_RETRY_BACKOFF_MS = int(os.getenv("KAFKA_RETRY_BACKOFF_MS", "1000"))
KAFKA_REQUEST_TIMEOUT_MS = int(os.getenv("KAFKA_REQUEST_TIMEOUT_MS", "30000"))
KAFKA_DELIVERY_TIMEOUT_MS = int(os.getenv("KAFKA_DELIVERY_TIMEOUT_MS", "120000"))
KAFKA_SEND_TIMEOUT_SECONDS = float(os.getenv("KAFKA_SEND_TIMEOUT_SECONDS", "10"))

__all__ = [
    "KAFKA_BOOTSTRAP_SERVERS",
    "SOCIAL_POSTS_TOPIC",
    "KAFKA_ACKS",
    "KAFKA_PRODUCER_RETRIES",
    "KAFKA_RETRY_BACKOFF_MS",
    "KAFKA_REQUEST_TIMEOUT_MS",
    "KAFKA_DELIVERY_TIMEOUT_MS",
    "KAFKA_SEND_TIMEOUT_SECONDS"
]
